#!/bin/bash
nodes=1
cpus=16
jobn=postprocessing

cd scripts

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166
#PBS -N $jobn
#PBS -q develop 
#PBS -j oe
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=$cpus:mem=16GB

module --force purge
module load ncarenv/25.10 uv

uv add numpy pandas h5py dask os

uv run python $file

EXEC

qsub < EXEC_STEP