#!/bin/bash
nodes=1
cpus=16
jobn=tracer-testing
file=domain_testing.py

cp $file scripts/
cp diagnostics.py scripts/
cp interpolation.py scripts/
cp reader.py scripts/
cp plotting_general.py scripts/
cp physics.py scripts/

cd scripts

cat > EXEC_STEP << EXEC
#!/bin/sh

#PBS -A UCUB0166
#PBS -N $jobn
#PBS -q develop 
#PBS -j oe
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=$cpus:mem=90GB

module --force purge
module load ncarenv/25.10 uv
###uv init
###uv add math
###uv add matplotlib
###uv add h5py
###uv add numpy
###uv add imageio
###uv add re
###uv add dask
uv run python $file

EXEC

qsub < EXEC_STEP